import type { CustomerMaster } from "@/domain/entities/customer";
import type { OpportunityMaster } from "@/domain/entities/opportunity";

const now = "2026-06-03T10:00:00.000Z";

export const SEED_CUSTOMERS: CustomerMaster[] = [
  {
    customer_id: "CU-88421",
    name: "Rajesh Kumar",
    mobile: "+91 98765 43210",
    mobile_normalized: "9876543210",
    email: "rajesh@email.com",
    address: "Mumbai, Maharashtra",
    customer_type: "Fleet Operator",
    created_at: now,
    updated_at: now,
  },
  {
    customer_id: "CU-90102",
    name: "Priya Sharma",
    mobile: "+91 87654 32109",
    mobile_normalized: "8765432109",
    email: null,
    address: "Delhi NCR",
    customer_type: "Individual",
    created_at: now,
    updated_at: now,
  },
  {
    customer_id: "CU-77201",
    name: "Amit Patel",
    mobile: "+91 76543 21098",
    mobile_normalized: "7654321098",
    email: null,
    address: "Pune, Maharashtra",
    customer_type: "Proprietorship",
    created_at: now,
    updated_at: now,
  },
  {
    customer_id: "CU-81200",
    name: "Kavita Joshi",
    mobile: "+91 43210 98765",
    mobile_normalized: "4321098765",
    email: "kavita@fleet.com",
    address: "Bengaluru, Karnataka",
    customer_type: "Fleet Operator",
    created_at: now,
    updated_at: now,
  },
  {
    customer_id: "CU-ABC-001",
    name: "ABC Logistics",
    mobile: "+91 99887 76655",
    mobile_normalized: "9988776655",
    email: "ops@abclogistics.in",
    address: "Chennai, Tamil Nadu",
    customer_type: "Fleet Operator",
    created_at: now,
    updated_at: now,
  },
];

function opp(
  partial: Omit<OpportunityMaster, "created_at" | "updated_at">,
): OpportunityMaster {
  return { ...partial, created_at: now, updated_at: now };
}

export const SEED_OPPORTUNITIES: OpportunityMaster[] = [
  opp({
    opportunity_id: "OP-2026-0154",
    customer_id: "CU-88421",
    product: "Tata Yodha",
    variant: "CLB PS",
    requirement: "Last mile delivery",
    opportunity_type: "New",
    current_stage: "C1",
    lifecycle_stage: null,
    current_micro_stage: "C1.5",
    current_owner: "Finance Executive",
    current_action: "Collect CIBIL Consent",
    next_action: "Generate Eligibility Report",
    next_action_date: "2026-06-03T18:00:00.000Z",
    priority: "P1",
    lead_score: 72,
    score_classification: "Warm",
    sla: "4 hrs",
    sla_due_at: "2026-06-03T14:00:00.000Z",
    sla_status: "On Track",
    escalation_owner: "Finance Manager",
    status: "Open",
    source: "Meta Ads",
    campaign: "Yodha Q2",
    branch: "Andheri",
    last_activity_at: now,
  }),
  opp({
    opportunity_id: "OP-2026-0201",
    customer_id: "CU-90102",
    product: "Tata Intra V70",
    variant: null,
    requirement: "Cold chain transport",
    opportunity_type: "Cross Sell",
    current_stage: "C0",
    lifecycle_stage: null,
    current_micro_stage: "C0.3",
    current_owner: "Sales Executive",
    current_action: "Complete qualification checklist",
    next_action: "Capture variant interest",
    next_action_date: "2026-06-03T15:30:00.000Z",
    priority: "P2",
    lead_score: 45,
    score_classification: "Cold",
    sla: "30 min",
    sla_due_at: "2026-06-03T10:30:00.000Z",
    sla_status: "At Risk",
    escalation_owner: "Sales Manager",
    status: "Open",
    source: "Website",
    campaign: null,
    branch: "Noida",
    last_activity_at: now,
  }),
  opp({
    opportunity_id: "OP-2026-0089",
    customer_id: "CU-77201",
    product: "Tata Ace",
    variant: "HT+",
    requirement: "Urban distribution",
    opportunity_type: "New",
    current_stage: "C0",
    lifecycle_stage: null,
    current_micro_stage: "C0.9",
    current_owner: "Sales Executive",
    current_action: "Confirm score gate for quote",
    next_action: "Move to quote ready",
    next_action_date: "2026-06-04T11:00:00.000Z",
    priority: "P4",
    lead_score: 58,
    score_classification: "Warm",
    sla: "1 hr",
    sla_due_at: "2026-06-03T11:00:00.000Z",
    sla_status: "On Track",
    escalation_owner: "Sales Manager",
    status: "Open",
    source: "Walk-in",
    campaign: null,
    branch: "Pune City",
    last_activity_at: now,
  }),
  opp({
    opportunity_id: "OP-2026-0312",
    customer_id: "CU-81200",
    product: "Tata Ultra",
    variant: "T.7",
    requirement: "Inter-city freight",
    opportunity_type: "Existing Customer",
    current_stage: "C2",
    lifecycle_stage: null,
    current_micro_stage: "C2.3",
    current_owner: "Billing Executive",
    current_action: "Collect billing documents",
    next_action: "Update disbursement status",
    next_action_date: "2026-06-03T17:00:00.000Z",
    priority: "P1",
    lead_score: 88,
    score_classification: "Hot",
    sla: "24 hrs",
    sla_due_at: "2026-06-02T17:00:00.000Z",
    sla_status: "Breached",
    escalation_owner: "Branch Head",
    status: "Open",
    source: "Google Ads",
    campaign: "Ultra Fleet",
    branch: "Whitefield",
    last_activity_at: now,
  }),
  opp({
    opportunity_id: "OP-2026-0401",
    customer_id: "CU-ABC-001",
    product: "Tata Ace",
    variant: "Gold",
    requirement: "City delivery fleet unit 1",
    opportunity_type: "Fleet Expansion",
    current_stage: "C1",
    lifecycle_stage: null,
    current_micro_stage: "C1.1",
    current_owner: "Sales Executive",
    current_action: "Share fleet quote",
    next_action: "Follow up on quote review",
    next_action_date: "2026-06-04T10:00:00.000Z",
    priority: "P2",
    lead_score: 65,
    score_classification: "Warm",
    sla: "24 hrs",
    sla_due_at: "2026-06-04T10:00:00.000Z",
    sla_status: "On Track",
    escalation_owner: "Sales Manager",
    status: "Open",
    source: "Existing Customer",
    campaign: null,
    branch: "Chennai Central",
    last_activity_at: now,
  }),
  opp({
    opportunity_id: "OP-2026-0402",
    customer_id: "CU-ABC-001",
    product: "Tata Intra V70",
    variant: "CLX",
    requirement: "Refrigerated transport",
    opportunity_type: "Cross Sell",
    current_stage: "C0",
    lifecycle_stage: null,
    current_micro_stage: "C0.4",
    current_owner: "Sales Executive",
    current_action: "Lock variant for cold chain",
    next_action: "Discuss budget band",
    next_action_date: "2026-06-05T10:00:00.000Z",
    priority: "P3",
    lead_score: 52,
    score_classification: "Warm",
    sla: "Same day",
    sla_due_at: "2026-06-03T18:00:00.000Z",
    sla_status: "On Track",
    escalation_owner: "Sales Manager",
    status: "Open",
    source: "Existing Customer",
    campaign: null,
    branch: "Chennai Central",
    last_activity_at: now,
  }),
  opp({
    opportunity_id: "OP-2026-0403",
    customer_id: "CU-ABC-001",
    product: "Tata Yodha",
    variant: "Pickup",
    requirement: "5 unit fleet expansion",
    opportunity_type: "Fleet Expansion",
    current_stage: "C0",
    lifecycle_stage: null,
    current_micro_stage: "C0.2",
    current_owner: "Sales Executive",
    current_action: "Capture fleet discovery",
    next_action: "Qualify fleet requirement",
    next_action_date: "2026-06-06T10:00:00.000Z",
    priority: "P2",
    lead_score: 70,
    score_classification: "Warm",
    sla: "Same day",
    sla_due_at: "2026-06-03T20:00:00.000Z",
    sla_status: "On Track",
    escalation_owner: "Branch Head",
    status: "Open",
    source: "Referral",
    campaign: null,
    branch: "Chennai Central",
    last_activity_at: now,
  }),
  opp({
    opportunity_id: "OP-2026-0404",
    customer_id: "CU-ABC-001",
    product: "School Bus",
    variant: "Starbus",
    requirement: "Institutional transport contract",
    opportunity_type: "New",
    current_stage: "C0",
    lifecycle_stage: null,
    current_micro_stage: "C0.1",
    current_owner: "Sales Executive",
    current_action: "Establish institutional contact",
    next_action: "Schedule discovery meeting",
    next_action_date: "2026-06-07T10:00:00.000Z",
    priority: "P3",
    lead_score: 40,
    score_classification: "Cold",
    sla: "48 hrs",
    sla_due_at: "2026-06-05T10:00:00.000Z",
    sla_status: "On Track",
    escalation_owner: "Sales Manager",
    status: "Open",
    source: "Tender",
    campaign: null,
    branch: "Chennai Central",
    last_activity_at: now,
  }),
];
