/**
 * Configurable Action Engine rules — from Consolidated Spec sheet 03.
 * Stage movement is Stage Master; these rules cover dynamic EVENT/TIME/STAGE logic.
 */

export type AutomationRuleType = "EVENT" | "TIME" | "STAGE";
export type AutomationRuleStatus = "ACTIVE" | "DRAFT" | "SHADOW" | "PAUSED" | "RETIRED";
export type ConditionOperator =
  | "IS_NOT_NULL"
  | "EQUALS"
  | "IN"
  | "NOT_EQUALS"
  | "GT"
  | "LT";

export interface AutomationRuleSeed {
  ruleCode: string;
  name: string;
  ruleType: AutomationRuleType;
  triggerEvent: string;
  scope: string;
  conditionGroup: "ALL" | "ANY";
  field: string;
  operator: ConditionOperator;
  expectedValue: string;
  actionType: string;
  actionOwnerLogic: string;
  priority: "P1" | "P2" | "P3" | "P4" | "P5";
  slaMinutes: number;
  escalationLogic: string;
  exitCondition: string;
  nextStage: string;
  status: AutomationRuleStatus;
  version: number;
}

export const AUTOMATION_RULE_SEEDS: AutomationRuleSeed[] = [
  {
    ruleCode: "C0_NEW_LEAD_VALIDATE",
    name: "Validate newly captured lead",
    ruleType: "EVENT" as AutomationRuleType,
    triggerEvent: "lead.created",
    scope: "Organisation/Branch",
    conditionGroup: "ALL" as "ALL" | "ANY",
    field: "lead.mobile",
    operator: "IS_NOT_NULL" as ConditionOperator,
    expectedValue: "true",
    actionType: "RUN_IDENTITY_RESOLUTION",
    actionOwnerLogic: "SYSTEM",
    priority: "P1" as AutomationRuleSeed["priority"],
    slaMinutes: 1,
    escalationLogic: "Technical alert if validation fails",
    exitCondition: "identity_check_completed = true",
    nextStage: "C0.2",
    status: "ACTIVE" as AutomationRuleStatus,
    version: 1,
  },
  {
    ruleCode: "C0_WA_ACTIVE_BOT",
    name: "Start bot for WhatsApp-active lead",
    ruleType: "EVENT" as AutomationRuleType,
    triggerEvent: "lead.contact_health_completed",
    scope: "Organisation/Branch/Product",
    conditionGroup: "ALL" as "ALL" | "ANY",
    field: "lead.whatsapp_status",
    operator: "EQUALS" as ConditionOperator,
    expectedValue: "ACTIVE",
    actionType: "START_BOT_JOURNEY",
    actionOwnerLogic: "BOT",
    priority: "P2" as AutomationRuleSeed["priority"],
    slaMinutes: 1,
    escalationLogic: "CRM manager if message not attempted",
    exitCondition: "bot_session_created = true",
    nextStage: "C0.4",
    status: "ACTIVE" as AutomationRuleStatus,
    version: 1,
  },
  {
    ruleCode: "C0_WA_READ_NO_REPLY",
    name: "Call WhatsApp read-no-reply lead",
    ruleType: "TIME" as AutomationRuleType,
    triggerEvent: "whatsapp.read",
    scope: "Organisation/Branch",
    conditionGroup: "ALL" as "ALL" | "ANY",
    field: "communication.reply_received",
    operator: "EQUALS" as ConditionOperator,
    expectedValue: "false",
    actionType: "CREATE_CALL_TASK",
    actionOwnerLogic: "AUTODIALER_QUEUE",
    priority: "P2" as AutomationRuleSeed["priority"],
    slaMinutes: 15,
    escalationLogic: "Telesales manager; reassign after 15 min",
    exitCondition: "call_disposition IS NOT NULL",
    nextStage: "C0.5",
    status: "ACTIVE" as AutomationRuleStatus,
    version: 1,
  },
  {
    ruleCode: "C0_HOT_CALLBACK",
    name: "Call explicit callback request",
    ruleType: "EVENT" as AutomationRuleType,
    triggerEvent: "customer.callback_requested",
    scope: "Organisation/Branch",
    conditionGroup: "ALL" as "ALL" | "ANY",
    field: "lead.priority",
    operator: "IN" as ConditionOperator,
    expectedValue: "HOT,CRITICAL",
    actionType: "CREATE_CALL_TASK",
    actionOwnerLogic: "SALES_EXECUTIVE",
    priority: "P1" as AutomationRuleSeed["priority"],
    slaMinutes: 5,
    escalationLogic: "Team leader at 5 min; reassign at 10 min",
    exitCondition: "call_connected OR valid_disposition",
    nextStage: "C0.6",
    status: "ACTIVE" as AutomationRuleStatus,
    version: 1,
  },
  {
    ruleCode: "C0_QUOTE_READY",
    name: "Validate quote readiness",
    ruleType: "STAGE" as AutomationRuleType,
    triggerEvent: "lead.qualification_completed",
    scope: "Organisation/Product",
    conditionGroup: "ALL" as "ALL" | "ANY",
    field: "qualification.mandatory_fields_complete",
    operator: "EQUALS" as ConditionOperator,
    expectedValue: "true",
    actionType: "CREATE_QUOTATION_TASK",
    actionOwnerLogic: "CURRENT_SALES_OWNER",
    priority: "P1" as AutomationRuleSeed["priority"],
    slaMinutes: 60,
    escalationLogic: "Sales manager if overdue",
    exitCondition: "quotation_created = true",
    nextStage: "C1.1",
    status: "ACTIVE" as AutomationRuleStatus,
    version: 1,
  },
  {
    ruleCode: "C1_QUOTE_FOLLOWUP",
    name: "Follow up shared quotation",
    ruleType: "TIME" as AutomationRuleType,
    triggerEvent: "quote.shared",
    scope: "Organisation/Branch",
    conditionGroup: "ALL" as "ALL" | "ANY",
    field: "quote.acknowledged",
    operator: "EQUALS" as ConditionOperator,
    expectedValue: "false",
    actionType: "CREATE_FOLLOWUP_TASK",
    actionOwnerLogic: "CURRENT_SALES_OWNER",
    priority: "P2" as AutomationRuleSeed["priority"],
    slaMinutes: 120,
    escalationLogic: "Team leader at SLA",
    exitCondition: "quote_acknowledged OR objection_captured",
    nextStage: "C1.2",
    status: "ACTIVE" as AutomationRuleStatus,
    version: 1,
  },
  {
    ruleCode: "C1_TEST_DRIVE",
    name: "Create test drive task",
    ruleType: "EVENT" as AutomationRuleType,
    triggerEvent: "test_drive.requested",
    scope: "Organisation/Branch/Product",
    conditionGroup: "ALL" as "ALL" | "ANY",
    field: "lead.status",
    operator: "EQUALS" as ConditionOperator,
    expectedValue: "OPEN",
    actionType: "SCHEDULE_TEST_DRIVE",
    actionOwnerLogic: "CURRENT_SALES_OWNER",
    priority: "P1" as AutomationRuleSeed["priority"],
    slaMinutes: 240,
    escalationLogic: "Sales manager if not scheduled same day",
    exitCondition: "test_drive_scheduled = true",
    nextStage: "C1.7",
    status: "ACTIVE" as AutomationRuleStatus,
    version: 1,
  },
  {
    ruleCode: "C1_MANAGER_INTERVENTION",
    name: "Escalate stuck hot lead",
    ruleType: "TIME" as AutomationRuleType,
    triggerEvent: "lead.stage_unchanged",
    scope: "Organisation/Branch",
    conditionGroup: "ALL" as "ALL" | "ANY",
    field: "lead.priority",
    operator: "IN" as ConditionOperator,
    expectedValue: "HOT,CRITICAL",
    actionType: "CREATE_MANAGER_INTERVENTION",
    actionOwnerLogic: "SALES_MANAGER",
    priority: "P1" as AutomationRuleSeed["priority"],
    slaMinutes: 30,
    escalationLogic: "Branch head after 30 min",
    exitCondition: "manager_action_recorded = true",
    nextStage: "C1.8",
    status: "ACTIVE" as AutomationRuleStatus,
    version: 1,
  },
  {
    ruleCode: "C1A_DOC_PENDING",
    name: "Escalate pending finance documents",
    ruleType: "TIME" as AutomationRuleType,
    triggerEvent: "finance.application_created",
    scope: "Organisation/Finance Partner",
    conditionGroup: "ALL" as "ALL" | "ANY",
    field: "finance.documents_complete",
    operator: "EQUALS" as ConditionOperator,
    expectedValue: "false",
    actionType: "CREATE_DOCUMENT_COLLECTION_TASK",
    actionOwnerLogic: "FINANCE_EXECUTIVE",
    priority: "P2" as AutomationRuleSeed["priority"],
    slaMinutes: 2880,
    escalationLogic: "Finance manager at 48 hours",
    exitCondition: "finance.documents_complete = true",
    nextStage: "C1A.2",
    status: "ACTIVE" as AutomationRuleStatus,
    version: 1,
  },
  {
    ruleCode: "C1A_FINANCE_REJECTED",
    name: "Route rejected finance case",
    ruleType: "EVENT" as AutomationRuleType,
    triggerEvent: "finance.rejected",
    scope: "Organisation/Branch",
    conditionGroup: "ANY" as "ALL" | "ANY",
    field: "finance.alternate_lender_available",
    operator: "EQUALS" as ConditionOperator,
    expectedValue: "true",
    actionType: "CREATE_ALTERNATE_FINANCE_TASK",
    actionOwnerLogic: "FINANCE_TEAM",
    priority: "P1" as AutomationRuleSeed["priority"],
    slaMinutes: 240,
    escalationLogic: "Finance manager if no alternate decision",
    exitCondition: "alternate_finance_started OR nurture_selected",
    nextStage: "C1A.1",
    status: "ACTIVE" as AutomationRuleStatus,
    version: 1,
  },
  {
    ruleCode: "C2_BOOKING_RECEIVED",
    name: "Create vehicle allocation action",
    ruleType: "EVENT" as AutomationRuleType,
    triggerEvent: "booking.payment_received",
    scope: "Organisation/Branch/Product",
    conditionGroup: "ALL" as "ALL" | "ANY",
    field: "booking.status",
    operator: "EQUALS" as ConditionOperator,
    expectedValue: "CONFIRMED",
    actionType: "ALLOCATE_VEHICLE",
    actionOwnerLogic: "STOCK_MANAGER",
    priority: "P1" as AutomationRuleSeed["priority"],
    slaMinutes: 240,
    escalationLogic: "Sales manager if stock not allocated",
    exitCondition: "vehicle_allocation_id IS NOT NULL",
    nextStage: "C2.2",
    status: "ACTIVE" as AutomationRuleStatus,
    version: 1,
  },
  {
    ruleCode: "C2_PDI_COMPLETE",
    name: "Move vehicle to delivery readiness",
    ruleType: "EVENT" as AutomationRuleType,
    triggerEvent: "pdi.approved",
    scope: "Organisation/Branch",
    conditionGroup: "ALL" as "ALL" | "ANY",
    field: "pdi.status",
    operator: "EQUALS" as ConditionOperator,
    expectedValue: "APPROVED",
    actionType: "CREATE_DELIVERY_READINESS_TASK",
    actionOwnerLogic: "DELIVERY_TEAM",
    priority: "P1" as AutomationRuleSeed["priority"],
    slaMinutes: 240,
    escalationLogic: "Delivery manager if overdue",
    exitCondition: "vehicle_ready = true",
    nextStage: "C3.1",
    status: "ACTIVE" as AutomationRuleStatus,
    version: 1,
  },
  {
    ruleCode: "C3_DELIVERY_DONE",
    name: "Activate lifecycle",
    ruleType: "EVENT" as AutomationRuleType,
    triggerEvent: "delivery.done",
    scope: "Organisation/Branch",
    conditionGroup: "ALL" as "ALL" | "ANY",
    field: "delivery.proof_complete",
    operator: "EQUALS" as ConditionOperator,
    expectedValue: "true",
    actionType: "ACTIVATE_LIFECYCLE",
    actionOwnerLogic: "SYSTEM",
    priority: "P2" as AutomationRuleSeed["priority"],
    slaMinutes: 1,
    escalationLogic: "Technical alert if lifecycle not created",
    exitCondition: "lifecycle_record_created = true",
    nextStage: "LIFECYCLE",
    status: "ACTIVE" as AutomationRuleStatus,
    version: 1,
  },
  {
    ruleCode: "LIFECYCLE_SERVICE_DUE",
    name: "Create service reminder action",
    ruleType: "TIME" as AutomationRuleType,
    triggerEvent: "service.due",
    scope: "Organisation/Branch",
    conditionGroup: "ALL" as "ALL" | "ANY",
    field: "customer_vehicle.status",
    operator: "EQUALS" as ConditionOperator,
    expectedValue: "ACTIVE",
    actionType: "SEND_SERVICE_REMINDER",
    actionOwnerLogic: "CRM_OR_SERVICE_TEAM",
    priority: "P3" as AutomationRuleSeed["priority"],
    slaMinutes: 1440,
    escalationLogic: "Service manager for missed first service",
    exitCondition: "reminder_sent OR service_booking_created",
    nextStage: "L1",
    status: "ACTIVE" as AutomationRuleStatus,
    version: 1,
  },
];

export function getActiveAutomationRules(): AutomationRuleSeed[] {
  return AUTOMATION_RULE_SEEDS.filter((r) => r.status === "ACTIVE");
}

export function getAutomationRule(code: string): AutomationRuleSeed | undefined {
  return AUTOMATION_RULE_SEEDS.find((r) => r.ruleCode === code);
}

